In [5]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5])
print(arr)

[1 2 3 4 5]


In [6]:
import numpy as np
print(np.__version__)

2.2.6


In [16]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[1:5])

[2 3 4 5]


In [13]:
import numpy as np

a = np.array(42)
b = np.array([1, 2, 3, 4, 5])
c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


In [14]:
import numpy as np

arr = np.array([1, 2, 3, 4], ndmin=5)

print(arr)
print('number of dimensions :', arr.ndim)

[[[[[1 2 3 4]]]]]
number of dimensions : 5


In [15]:
import numpy as np

arr = np.array([1, 2, 3, 4])

print(arr[0])

1


In [1]:
pip install pygame

   ---------------------------------------- 0.0/10.6 MB ? eta -:--:--
   ---- ----------------------------------- 1.3/10.6 MB 22.3 MB/s eta 0:00:01
   ----------------- ---------------------- 4.7/10.6 MB 13.6 MB/s eta 0:00:01
   -------------------- ------------------- 5.5/10.6 MB 9.9 MB/s eta 0:00:01
   --------------------- ------------------ 5.8/10.6 MB 7.0 MB/s eta 0:00:01
   ---------------------- ----------------- 6.0/10.6 MB 5.6 MB/s eta 0:00:01
   ----------------------- ---------------- 6.3/10.6 MB 5.1 MB/s eta 0:00:01
   ------------------------- -------------- 6.8/10.6 MB 4.7 MB/s eta 0:00:01
   ----------------------------- ---------- 7.9/10.6 MB 4.6 MB/s eta 0:00:01
   ---------------------------------- ----- 9.2/10.6 MB 4.8 MB/s eta 0:00:01
   ---------------------------------------- 10.6/10.6 MB 5.0 MB/s eta 0:00:00
Note: you may need to restart the kernel to use updated packages.
